disp('多维多类特征提取Fisher');
disp('本程序依赖libFisher_XXXX(四个)');
disp('y为标签向量，暂时只支持数字');
disp('x为数据矩阵，不论纵横，只要和y对齐即可，本lib会自己翻转来着~');
disp('例如y是行向量，那么每一个x向量都是列向量。');
disp(' ');
disp('varargin=[dim,beta,Method]');
disp('dim是分解出的W中的w的数量，各个w之间是正交的，w的范数都是1。');
disp('beta是辅助矩阵的参数ξ');
disp('Method是多类多维时的方法参数，是先单类Fisher以后再做特征值提取还是直接特征值提取（默认）');
disp(' ');
disp('详细用法请看三个单元测试');
disp(' (*_*)oOO ');
